### ISSUE TITLE
App doesn't vibrate.

### ISSUE THREAD

**Issue by lalitahuja33** [PPartisan/Simple-Alarms#5]
The app doesn't vibrate/plays music or shows any notification on the time of the alarm what should I do. And can you tell me the Activity/function which handles this condition of matching the system time with the set alarm time?

**Comment by PPartisan** [comment]
Which version of Android are you using, and do you see any output in LogCat around the time the alarm is supposed to go off?

**Comment by lalitahuja33** [comment]
I'm using android marshmallow(6.0.1) and Android studio version 3.2.
Can you tell me the activity/function in which the app is comparing the system time with the set time for alarm? I'm new to the android studio and unable to understand the code completely.

Here's the LogCat output at the time
`03-12 20:27:06.827 8949-8949/com.github.ppartisan.simplealarms D/AndroidRuntime: Shutting down VM
03-12 20:27:06.828 8949-8949/com.github.ppartisan.simplealarms E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.github.ppartisan.simplealarms, PID: 8949
    java.lang.RuntimeException: Unable to start receiver com.github.ppartisan.simplealarms.service.AlarmReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.github.ppartisan.simplealarms.model.Alarm.getId()' on a null object reference
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2813)
        at android.app.ActivityThread.access$2000(ActivityThread.java:154)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5613)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.github.ppartisan.simplealarms.model.Alarm.getId()' on a null object reference
        at com.github.ppartisan.simplealarms.util.AlarmUtils.getNotificationId(AlarmUtils.java:155)
        at com.github.ppartisan.simplealarms.service.AlarmReceiver.onReceive(AlarmReceiver.java:33)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2806)
        at android.app.ActivityThread.access$2000(ActivityThread.java:154) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5613) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652) 
03-12 20:27:06.937 8949-8949/com.github.ppartisan.simplealarms I/Process: Sending signal. PID: 8949 SIG: 9 of alarm:`

Additionally, there are a couple of functions in the code which are never used/called.

**Comment by PPartisan** [comment]
Take a look at the solution for issue #2

**Comment by lalitahuja33** [comment]
The notification problem is solved.
I'm trying to add a spinner to the app. It's successfully added to the fragment_add_edit_alarm.xml but the selected values are not showing in the Textview of alarm_row.xml. Can you please help me with that I'm a beginner in Android development.

**Comment by PPartisan** [comment]
Best make a post on [StackOverflow](https://stackoverflow.com/), and follow the posting guidelines there, if you're having an issue. I'll close this as resolved.
